In [69]:
import pandas as pd
import numpy as np
df_train = pd.read_csv('DMProj1/train.csv')
df_resources = pd.read_csv('DMProj1/resources.csv')
df_resources['Total_cost'] = df_resources.quantity * df_resources.price
train_resource = pd.merge(df_train, df_resources, on="id", how='left')
#https://www.kaggle.com/codename007/a-very-extensive-end-to-end-project-donorschoose
## Merging with train and test data ##
train_resource = pd.merge(df_train, df_resources, on="id", how='left')

Total_cost = train_resource.pivot_table(values=['Total_cost','quantity'],
                                        index='id',
                                        aggfunc={'Total_cost' : np.sum, 'quantity' : np.sum})
Total_cost.reset_index(level=0, inplace = True)

df_train = df_train.merge(Total_cost, on='id', how='left')
df_train['Average_item_cost'] = df_train.Total_cost  / df_train.quantity

In [70]:
df_train.describe()

,teacher_number_of_previously_posted_projects,project_is_approved,Total_cost,quantity,Average_item_cost
count,182080.000000,182080.000000,182080.000000,182080.000000,182080.000000
mean,11.237055,0.847682,545.748958,16.971447,117.882182
std,28.016086,0.359330,548.198713,26.241957,273.689634
min,0.000000,0.000000,100.000000,1.000000,0.258889
25%,0.000000,1.000000,245.997500,4.000000,17.042452
50%,2.000000,1.000000,397.750000,9.000000,45.954722
75%,9.000000,1.000000,691.920000,21.000000,135.704464
max,451.000000,1.000000,15299.690000,930.000000,9999.000000